### ISSUE TITLE
Moving connections between server instances

### ISSUE THREAD

**Issue by martinthomson** [quicwg/load-balancers#10]
Some text on how a server cluster might support moving of connections from one server instance to another would be useful.  The current design might permit portability under certain conditions, but there are things that might need to be considered, such as the way in stateless resets are generated.

**Comment by nibanks** [comment]
Are you referring to load balancing already existing connections to a new server? Are you envisioning the first server issuing new CIDs (that point to the new server) and setting Retire Prior To to retire the old CIDs so that future traffic redirect to the new server? How do you imagine the rest of the connection state would get moved?

**Comment by martinthomson** [comment]
This applies to cases where clusters are rebalanced, where instances go down and others are expected to pick up the slack, and all similar cases.  In some cases this requires an unspecified mechanism for transferring state between instances.  In others, the instance might remain constant but the identifiers used might need to rotate.

This is likely addressed by using Retire Prior To as you say.  Text on that would help.

**Comment by martinduke** [comment]
Good idea, it wouldn't hurt to have a short non-normative section on this.
