### ISSUE TITLE
Using ECB for retry tokens seems sub optimal

### ISSUE THREAD

**Issue by huitema** [quicwg/load-balancers#35]
Section 5.3 specifies a  Shared-State Retry Service describes a token format in which the token include the ODCID, a client IP encoded on 128 bits, and a 20 octets data-time, plus additional data. The token is encrypted using AES ECB. This seems sub-optimal:

1) Using AES GCM or another AEAD format seems more natural. AEAD checks will immediately detect an invalid token, while using ECB forces reliance on invalidity heuristics.

2) If using AEAD, there is no need to encode the IP address in the token. It can be derived from the IP header and placed in a pseudo header. The pseudo header can then be authenticated as part of AEAD decryption.

3) The pseudo header approach can be used to authenticate other fields, e.g. verify that the DCID matches the SCID sent in the Retry packet.

4) Encoding the time as 64 bits time64_t seems more natural than ASCII encoding, and also shorter.

**Comment by huitema** [comment]
The editor draft also encodes the server's SCID in the token. That too could be moved to a pseudo-header, since the field is assume present in the DCID of the post retry Initial.

**Comment by martinduke** [comment]
Closed by #33

**Comment by martinduke** [comment]
This was closed in error, as #33 deals with the Stream Cipher.

**Comment by martinduke** [comment]
I filed a very similar issue and then closed it when I realized the duplication. The text of that issue:

I'm not an encryption expert, but if IIUC it's insufficiently hard to forge a shared-state retry token.

By inducing a Retry, an attacker can obtain the Retry SCID Length, and then focus entirely on an ODCIDs that allow the CID + CID Length part of the token to be a multiple of 16 B. For example, if RSCIDL= 10 B, then make ODCIDL = 20 B -> 32 Bytes for the block.

This then breaks Retry forgery into three separate problems:
(1) Obtaining the mapping of IP Address to the first 16 Bytes of the token. A well-positioned observer could build a database of these in the time scale between token key rotations.
(2) Generate lots of Retry tokens with an ODCID of the correct length, so there is a range of valid CID blocks.
(3) Obtain a valid Retry every few seconds, using the right ODCID length, so that we have a valid timestamp.

Thus, the attacker has a database of

valid encrypted IP addresses
valid encrypted CIDs (really, it's the CID length that would cause validation to fail)
valid timestamps
As the spec uses AES-ECB, these blocks can be mixed and matched to create valid Retry tokens.

This is not exactly trivially open to attack [1], but it does feel like we're conceding a lot of entropy here. I would like someone to propose an alternate design that restores some of that entropy.

[1] Step (1) seems to require a fairly privileged position in the network.

**Comment by martinduke** [comment]
@huitema Could I trouble you for a PR on this?

**Comment by huitema** [comment]
Sure. I can basically propose what I am doing in picoquic.
And yes, the repetitive nature of ECB enables attacks.

**Comment by huitema** [comment]
@martinduke please review PR #59
