### ISSUE TITLE
Unguessable connection IDs

### ISSUE THREAD

**Issue by martinthomson** [quicwg/load-balancers#8]
There is a requirement that it be difficult for a party other than the server and load balancer to guess a CID that will be accepted as valid for a target connection.

This requirement needs to be validated for the schemes described in the draft.  This might impose some constraints on the designs chosen.

For instance, I don't believe that the plaintext algorithm meets this goal.  The server ID can take all the available space, which is probably wrong.  Clearly it is impossible to create sufficient connection IDs for even a single connection if there is only one valid identifier per server.  However, it might be argued that even an 18 byte server ID makes it too easy to guess a valid connection ID for a connection (just 16 guesses would be enough to get a 50% chance at that).  So it seems to me that a shorter connection ID is necessary.

The same applies to any attempt at obfuscation.

The encrypted versions might be similarly challenging to get right.  The For Server Use field in the stream cipher variant needs to be sufficiently long as to avoid engineered collisions.  The value used for the stream cipher is malleable, which means that an attacker isn't prevented from guessing.  In many ways, this is more challenging than the plaintext variant because the nonce consumes space.

The zero-padding in the block cipher mode might be the best way of preventing guessing, if it were sufficiently long.  Similarly, if "Encrypted bits for server use" were sufficiently sparsely populated, then guessing can be hard enough.

**Comment by nibanks** [comment]
> There is a requirement that it be difficult for a party other than the server and load balancer to guess a CID that will be accepted as valid for a target connection.

- What exactly does "a CID that will be accepted as valid for a target connection" mean?
- What is exactly making this requirement?

**Comment by martinthomson** [comment]
A connection ID that is accepted as valid for a target connection is any value that will cause packets to be routed to the node that serves that connection.

The transport draft [says](https://quicwg.org/base-drafts/draft-ietf-quic-transport.html#section-5.1-3):

> Connection IDs MUST NOT contain any information that can be used by an external observer (that is, one that does not cooperate with the issuer) to correlate them with other connection IDs for the same connection.

**Comment by martinduke** [comment]
I think this issue is conflating two different things:
1) Is it easy to generate a CID that has a high probability of being considered valid by the LB? For all but BCID with zero-padding, the answer is clearly "yes" unless the SID space is sparsely populated. But that doesn't make them valid at the server. Moreover, if I am just trying to get random packets past the LB, it's far more productive to just generate a bunch of Initials.

In the absence of an LB, all CIDs get through to the server, so I don't understand why this is a problem.

2) The transport draft language (it seems to me) exists mostly to prevent linkability in migration events. Although I've mentioned several times that linkability is a continuum, it is pretty clear that PCID fails at this and OCID makes it harder but no one would bet the house on it being truly secure -- hence the name.

I think we're due for an actual WG discussion on OCID, but for PCID would it be sufficient for you, MT, if we said that servers using PCID MUST use disable_migration? To be honest, I thought I had already done this but it's not there.

**Comment by nibanks** [comment]
I really want to push back hard on any restrictions around migration for the Plaintext CID algorithm. It is by far the simplest and cheapest algorithm to support in the LB, and IMO must remain a valid option for QUIC load balancing.

As far as giving any information to an external observer, it's possible an external observer can work out the Server ID for each CID. Whether this is practically useful information depends on the number of connections being managed by the individual servers.

IMO, we cannot restrict the full set of QUIC features to only work on the most complex and costly algorithms. Some solutions may never implement them.

**Comment by martinduke** [comment]
Ah wait, I found the text in security considerations:

> Servers that are running the Plaintext CID  algorithm SHOULD only use it to generate new CIDs for the Server Initial Packet and SHOULD NOT send CIDs in QUIC NEW_CONNECTION_ID frames.  Doing so might falsely suggest to the client that said CIDs were generated in a secure fashion.

So it's a SHOULD right now.

**Comment by martinduke** [comment]
To summarize the issue with Plaintext CID. This is the easiest to implement, so is mostly likely to be adopted.

However:
1) This makes DoS attacks on a single server quite straightforward. There is no consensus as to whether single-server DoS is a threat to mitigate or not.
2) Makes connection IDs more linkable.
3) Unless we add a server transport parameter for it, the client has no idea they're more linkable.
4) We could prohibit migration to fix the linkability problem.
5) If we prohibit migration, than the only reason to do plaintext CIDs, instead of just 5-tuple routing, is to support NAT rebinding.

To some extent, Obfuscated CID might have similar issues.

**Comment by martinduke** [comment]
The discussion at IETF 109 suggested that the level of linkability associated with the PCID algorithm did not violate the spirit of quic-transport (see @martinthomson and @ianswett in the QUIC-LB segment here: https://datatracker.ietf.org/meeting/109/materials/minutes-109-quic-00)
